### ISSUE TITLE
Make status page look like it's in the main site

### ISSUE THREAD

**Issue by tseemann** [gvlproject/gvl-website-markdown#1]
And keep the Nav bar etc?

**Comment by madisonkeene** [comment]
Yeah this is not as easy as you think - a lot of the CSS/HTML is controlled by the open source status page package itself. For e.g. the text in the current status header is actually a screenshot from the GVL website... I was in a bit of a rush to push it out though, so will leave open and add to my to-do list to investigate :)

**Comment by madisonkeene** [comment]
Well that was a pain... but this is as good as it's gonna get: http://status.genome.edu.au/
