### ISSUE TITLE
Shrink people photos

### ISSUE THREAD

**Issue by tseemann** [gvlproject/gvl-website-markdown#2]
The photos of people take ages to load because they are full resolution:
https://www.genome.edu.au/people/

Downsample them?

```
mkdir new
for N in *.jpg ; do convert -resize 256x $N new/$N ; done
```

**Comment by madisonkeene** [comment]
Added to my to-do list :)

**Comment by madisonkeene** [comment]
Done - turns out when you upload a pic to wordpress media library it uploads it in multiple diff sizes
