### ISSUE TITLE
Move status page to gvl.org.au

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/gvl-website-markdown#5]
move status.genome.edu.au to status.gvl.org.au
Madi to change stuff in status page itself then change DNS.

**Comment by nuwang** [comment]
Have also updated website menus. Works well. Do we need https?

**Comment by madisonkeene** [comment]
Thanks @nuwang forgot about those :) Not 100% sure how to do https (it all runs out of docker)- don't think its essential for now, and we cant anyway till we get SSL certs which probably won't happen before I leave. Closing this for now, and you guys can investigate https in 2017 once you have certs :)
