### ISSUE TITLE
Google shows the website title as 'Microbial Genomics Virtual Lab'

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/gvl-website-markdown#8]
This should probably be just 'Genomics Virtual Lab'
Not sure where that setting lives in Wordpress.

**Comment by Slugger70** [comment]
Can't find it on wordpress anywhere.. Almost no mention of "microbial" gvl...

Could it just be from cumulative searches?

**Comment by madisonkeene** [comment]
TIL that google generates the titles in it's search results! Crazy. I just assumed the `<title>` was wrong ha. Possibly worth adding a meta tag or something though to eventually trick google into changing it back... see the link below.
https://support.google.com/webmasters/answer/35624?hl=en

**Comment by madisonkeene** [comment]
This seems to have resolved itself for me now.
